SELECT MONTHNAME(BILLING.CHARGED_DATETIME) as 'month',SUM(amount) as 'revenue' FROM BILLING WHERE BILLING.CHARGED_DATETIME LIKE "2012-03%" 
SELECT SUM(amount) as 'Revenue for Client ID 2' FROM BILLING WHERE client_id = 2
SELECT * FROM SITES WHERE CLIENT_ID = 10
SELECT sites.client_id, Count(sites.domain_name) as 'number of websites', MONTHNAME(sites.created_datetime) as 'Month', YEAR(sites.created_datetime) as 'Year' FROM sites where sites.client_id = 1 group by MONTHNAME(sites.created_datetime), YEAR(sites.created_datetime) ORDER BY YEAR(sites.created_datetime) ASC
SELECT sites.client_id, Count(sites.domain_name) as 'number of websites', MONTHNAME(sites.created_datetime) as 'Month', YEAR(sites.created_datetime) as 'Year' FROM sites where sites.client_id = 20 group by MONTHNAME(sites.created_datetime), YEAR(sites.created_datetime) ORDER BY YEAR(sites.created_datetime) ASC
SELECT SITES.DOMAIN_NAME, count(leads.leads_id) as '# of Leads',sites.CREATED_DATETIME FROM SITES, leads WHERE SITES.site_id  = leads.site_id and leads.registered_datetime > '2011-01-1' and leads.registered_datetime < '2011-02-15' group by SITES.domain_name
SELECT CONCAT(CLIENTS.first_name, " ", clients.last_name) as 'client_name',  count(leads.leads_id) as '# of leads' FROM CLIENTS, LEADS, SITES where sites.client_id = clients.client_id  and leads.site_id = sites.site_id and leads.registered_datetime > '2011-01-1' and leads.registered_datetime < '2011-12-31'group by clients.client_id
SELECT CONCAT(clients.first_name, " " , clients.last_name) as Client, COUNT(MONTH(registered_datetime)) AS Lead_Count, MONTHNAME(registered_datetime) AS Month, YEAR(registered_datetime) AS Year FROM clients JOIN sites ON sites.client_id = clients.client_id JOIN leads ON leads.site_id = sites.site_id WHERE YEAR(registered_datetime) = 2011 AND MONTH(registered_datetime) > 0 AND MONTH(registered_datetime) < 7 GROUP BY clients.client_id, MONTH(registered_datetime) ORDER BY MONTH(registered_datetime), clients.client_id;
SELECT CONCAT(clients.first_name, " " , clients.last_name) as Client,  sites.domain_name, COUNT(sites.domain_name) AS Lead_Count, DATE_FORMAT(leads.registered_datetime, "%M %D, %Y") as 'date' FROM clients, leads, sites WHERE sites.client_id = clients.client_id and leads.site_id = sites.site_id and YEAR(registered_datetime) = 2011 AND MONTH(registered_datetime) > 0 AND MONTH(registered_datetime) < 13 GROUP BY clients.client_id, sites.domain_name
SELECT CONCAT(clients.first_name, " " , clients.last_name) as Client,  sites.domain_name, COUNT(sites.domain_name) AS Lead_Count, DATE_FORMAT(leads.registered_datetime, "%M %D, %Y") as 'date' FROM clients, leads, sites WHERE sites.client_id = clients.client_id and leads.site_id = sites.site_id GROUP BY clients.client_id, sites.domain_name
SELECT CONCAT(clients.first_name, " ", clients.last_name) as 'client name', SUM(billing.amount), MONTHNAME(billing.charged_datetime) as 'month', YEAR(billing.charged_datetime) as 'year' FROM  clients JOIN BILLING ON billing.client_id = clients.client_id GROUP BY CLIENTS.CLIENT_ID, YEAR(BILLING.CHARGED_DATETIME), MONTH(BILLING.CHARGED_DATETIME) ORDER BY CLIENTS.CLIENT_ID, YEAR(BILLING.CHARGED_DATETIME), MONTH(BILLING.CHARGED_DATETIME)
SELECT CONCAT(clients.first_name, " ", clients.last_name) as 'client name', GROUP_CONCAT(sites.domain_name SEPARATOR ' / ') as 'sites' FROM clients JOIN SITES ON CLIENTS.CLIENT_ID = SITES.CLIENT_IDGROUP BY CLIENTS.CLIENT_ID;