SELECT address.city_id, city.city, customer.first_name, customer.last_name, customer.email, address.address from customer, address, city where customer.address_id = address.address_id and city.city_id = address.city_id and address.city_id = 312
SELECT film.title, film.description, film.release_year, film.rating, film.special_features, category.name as 'genre' 
from film, category, film_category 
where film_category.film_id = film.film_id 
and  film_category.category_id = category.category_id 
and category.name = 'Comedy'
SELECT film_actor.actor_id, concat(actor.first_name, " ", actor.last_name) as 'actor_name', film.film_id,  film.title,  film.description, film.release_year from film join film_actor on film_actor.film_id = film.film_id join actor on film_actor.actor_id = actor.actor_id where actor.actor_id = 5
SELECT store.store_id, city.city_id, customer.first_name, customer.last_name, customer.email, address.address from store, city, customer, address where address.address_id = customer.address_id and customer.store_id = store.store_id and city.city_id = address.city_id and store.store_id = 1 and (city.city_id = 1 or city.city_id = 42  or city.city_id = 312 or city.city_id = 459)
SELECT film.title, film.description, film.release_year, film.rating, film.special_features from film join film_actor on film_actor.film_id = film.film_id  join actor on film_actor.actor_id = actor.actor_id where film.rating = 'G' and film.special_features like "%Behind the Scenes%" and actor.actor_id = 15
SELECT film.film_id, concat(actor.first_name, " ", actor.last_name) as 'actor_name', film_actor.actor_id, film.title from film join film_actor on film_actor.film_id = film.film_id join actor on film_actor.actor_id = actor.actor_id where film.film_id = 369
SELECT film.film_id, film.title, film.description, film.release_year, film.rating, film.special_features, category.name as 'genre', film.rental_rate from film, category, film_category where film_category.film_id = film.film_id and  film_category.category_id = category.category_id and category.name = 'Drama' and film.rental_rate = 2.99
SELECT film_actor.actor_id, concat(actor.first_name, " ", actor.last_name) as 'actor_name', film.film_id,  film.title,  film.description, film.release_year, category.name from film join film_actor on film_actor.film_id = film.film_id join actor on film_actor.actor_id = actor.actor_id join film_category on film_category.film_id = film.film_id join category on film_category.category_id = category.category_id where concat(actor.first_name, " ", actor.last_name) = 'Sandra Kilmer' and category.name = 'Action';