# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0002_auto_20180218_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='authors', to='books_authors.authors'),
        ),
    ]
