# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default='Coding Bootcamp that teaches 3 stacks', max_length=255),
            preserve_default=False,
        ),
    ]
