var number1 = -3;
var number2 = 45;
var number3 = 1.5;
var number4 = 1001;
var string1 = "Coding";
var string2 = "Dojo";
var boolean1 = true;
var boolean2 = false;
var undefinedVar;
console.log('First Number: '+ number1);
console.log('Second Number: '+ number2);
console.log('Third Number: '+ number3);
console.log('Fourth Number: '+ number4);
console.log('First String: '+ string1);
console.log('Second String: '+ string2);
console.log('First Boolean: '+ boolean1);
console.log('Second Boolean: '+ boolean2);
console.log('Undefined variable: '+ undefinedVar);